title: zergling
author: zergling
email: kjs36202@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  수학과 다니는 평범한 보안쟁이
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: zergling
  tagline: hacker
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/profile_image.jpeg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: samarsault
    github:  kjs36202
    #linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    instagram: sj_mik
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    soundcloud: kjs36202
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag